# Generated by Django 2.0.7 on 2018-08-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('descricao', models.CharField(blank=True, max_length=80, null=True, verbose_name='Descrição')),
                ('valorunitario', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Valor Unitário')),
                ('quantidadedeestoque', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Quantidade de Estoque')),
            ],
        ),
    ]
